language: java

matrix:
  include:
    - os: linux
      dist: xenial
      jdk: openjdk8
      addons:
        apt:
          packages:
            - libvulkan-dev
            - build-essential
            - libevent-pthreads-2.0.5
            - doxygen
            - xorg-dev
            - libglu1-mesa-dev
    - os: osx
      osx_image: xcode10

before_cache:
  - brew cleanup

cache:
  directories:
    - $HOME/Library/Caches/Homebrew

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      PATH=$(echo "$PATH" | sed -e 's/:\/usr\/local\/lib\/jvm\/openjdk11\/bin//')
      JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64

      git clone https://github.com/glfw/glfw.git
      cd glfw
      cmake .
      make
      sudo make install
      cd ..
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update
      brew install glfw --HEAD
    fi

script:
  - ./gradlew build
